INSERT INTO CUSTOMER_TABLE (CUSTOMER_TABLE_ID) VALUES (1);
INSERT INTO CUSTOMER_TABLE (CUSTOMER_TABLE_ID) VALUES (2);
INSERT INTO CUSTOMER_TABLE (CUSTOMER_TABLE_ID) VALUES (3);
INSERT INTO CUSTOMER_TABLE (CUSTOMER_TABLE_ID) VALUES (4);
INSERT INTO CUSTOMER_TABLE (CUSTOMER_TABLE_ID) VALUES (5);

--INSERT INTO CUSTOMER_ORDER(CUSTOMER_ORDER_ID, CUSTOMER_TABLE_ID) VALUES (1, 1);

--INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ITEM_NAME, CUSTOMER_ORDER_ID) VALUES (1, 'Latte', 1);
--INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ITEM_NAME, CUSTOMER_ORDER_ID) VALUES (2, 'Espresso', 1);